cluster:
  name: placeholder
  baseDomain: lab.signal9.gg
  # Maybe kubevirt or agent
  type: kubevirt
  # This namespace must already exist on the cluster
  hcpNamespace: clusters
  # This is required for disconnected installs as of 4.14.9
  controlPlaneOperatorImageOverride: null
  #controlPlaneOperatorImageOverride: quay.rho.lab.signal9.gg:8443/mirror/openshift/release@sha256:cd603d06b6da4610d3c0e5c9cab466048cbdf7dae6eac3d0e062707db7be29f1
  releaseImage: quay.io/openshift-release-dev/ocp-release:4.14.9-x86_64
  foundationIngressBaseDomain: apps.zardoz.lab.signal9.gg
  importToACM: true
  etcd:
    storageClassName: "longhorn"
    size: 8Gi
  pullSecretVault: "ocp-pull-secret"
  trustBundleConfigMap: user-ca-bundle
  networking:
    clusterNetwork:
      cidr: 10.128.0.0/14
      hostPrefix: 23
    serviceNetwork:
      cidr: 172.30.0.0/16
  services:
    api:
      type: LoadBalancer
      # If using nodePort, comment out above line, uncomment below and set port
      # type: nodePort
      # port: 30000
  sshPubKey: ""
  kubevirt:
    # If true, use a subdomain of the foundation cluster's ingress for workload ingress
    baseDomainPassthrough: true
    # If you use external infrastructure for KubeVirt
    # external:
    #   # Point to secret containing kubeconfig for kubevirt cluster
    #   kubeconfigSecret: kubeconfigsecret
    #   kubeconfigKey: kubeconfig
  agent:
    createInfraEnv: true
    # Defaults to a new per-cluster namespace
    agentNamespaceOverride: null
  proxy:
    httpProxy: ""
    httpsProxy: ""
    noProxy: kubernetes,
certManager:
  manageApiCert: true
  manageOauthCert: true
  # Ingress certificate will be created, but deployment requires an ACM policy or gitops
  manageIngressCert: true

nodePools:
  - name: worker
    count: 3
    kubevirt:
      resources:
        cpu: 2
        memory: 8Gi
        rootVolumeSize: 120Gi
      enableRootVolumeCache: true
    agent:
      agentLabels: {}
    nodeDrainTimeout: 600s
    # enable if you have custom node configurations
    nodeconfig:
      - name: some-cluster-cm
      - name: some-other-cm
    management:
      autoRepair: false
      # InPlace for BM, Replace for Kubevirt
      upgradeType: Replace

agent:
  imageType: full-iso
  infraEnv:
    networkType: static
    ntpServers:
      - 172.18.0.79
      - 172.18.42.10
      - 172.18.42.11

imageDigestMirror: []

# Additional trust bundle for the cluster
additionalTrustBundle: []
