apiVersion: hypershift.openshift.io/v1beta1
kind: HostedCluster
metadata:
  name: {{ .Values.cluster.name }}
  namespace: {{ .Values.cluster.hcpNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: '2'
{{- if .Values.cluster.controlPlaneOperatorImageOverride }}
    hypershift.openshift.io/control-plane-operator-image: {{ .Values.cluster.controlPlaneOperatorImageOverride }}
{{ end }}
spec:
  autoscaling: {}
{{- if .Values.cluster.trustBundleConfigMap }}
  additionalTrustBundle:
    name: {{ .Values.cluster.trustBundleConfigMap }}
{{ end }}
  controllerAvailabilityPolicy: HighlyAvailable
  olmCatalogPlacement: guest
  dns:
{{- if and (eq .Values.cluster.type "kubevirt") (.Values.cluster.kubevirt.baseDomainPassthrough) }}
    baseDomain: "{{ .Values.cluster.foundationIngressBaseDomaion }}"
{{ else }}
    baseDomain: {{ .Values.cluster.baseDomain }}
{{ end }}
  configuration:
    {{- if or .Values.certManager.manageApiCert .Values.certManager.manageOauthCert }}
    apiServer:
      audit:
        profile: Default
      servingCerts:
        namedCertificates:
    {{- if .Values.certManager.manageApiCert  }}
        - names:
          - api.{{ .Values.cluster.name }}.{{ .Values.cluster.baseDomain }}
          servingCertificate:
            name: {{ .Values.cluster.name }}-api-crt
    {{ end }}
    {{- if .Values.certManager.manageOauthCert  }}
        - names:
          - oauth-clusters-{{ .Values.cluster.name}}.{{ .Values.cluster.foundationIngressBaseDomain }}
          servingCertificate:
            name: {{ .Values.cluster.name }}-api-crt
    {{ end }}
    {{- end }}
    oauth:
      identityProviders:
        - name: local-admin 
          mappingMethod: claim
          type: HTPasswd
          htpasswd:
            fileData:
              name: local-admin-htpass
        - mappingMethod: claim
          name: Signal9-RHT
          openID:
            claims:
              email:
              - email
              groups:
              - groups
              name:
              - name
              preferredUsername:
              - preferred_username
              - email
            clientID: {{ .Values.cluster.name }}-openshift
            clientSecret:
              name: {{ .Values.cluster.name }}-oauth-client-secret
            extraScopes:
            - profile
            issuer: https://login.home.signal9.gg/realms/Signal9-RHT
          type: OpenID
  {{-  if .Values.cluster.proxy }}
    proxy:
      httpProxy: {{ .Values.cluster.proxy.httpProxy }}
      httpsProxy: {{ .Values.cluster.proxy.httpsProxy }}
      noProxy: {{ .Values.cluster.proxy.noProxy }}
      trustedCA:
        name: {{ .Values.cluster.proxy.caBundle }}
  {{- end }}
  etcd:
    managed:
      storage:
        persistentVolume:
          {{- if .Values.cluster.etcd.storageClassName }}
          storageClassName: {{ .Values.cluster.etcd.storageClassName }}
          {{- end }}
          size: {{ .Values.cluster.etcd.size }}
        type: PersistentVolume
    managementType: Managed
  fips: false
  networking:
    clusterNetwork:
    - cidr: {{ .Values.networking.clusterNetwork.cidr | default "10.132.0.0/14" }}
      hostPrefix: {{ .Values.networking.clusterNetwork.hostPrefix | default 23 }}
    networkType: OVNKubernetes
    serviceNetwork:
    - cidr: {{ .Values.networking.serviceNetwork.cidr | default "172.31.0.0/16" }}
  platform:
{{- if eq .Values.cluster.type "agent" }}
    agent:
      agentNamespace: {{ .Values.cluster.agent.agentNamespaceOverride | default (print "clusters-" .Values.cluster.name) }}
    type: Agent
{{- end }}
{{- if eq .Values.cluster.type "kubevirt" }}
  platform:
    kubevirt:
      baseDomainPassthrough: {{ .Values.cluster.kubevirt.baseDomainPassthrough }}
      {{- if .Values.cluster.kubevirt.external }}
      credentials:
        infraKubeConfigSecret:
          name: {{ .Values.cluster.kubevirt.external.kubeconfigSecret }}
          key: {{ .Values.cluster.kubevirt.external.kubeconfigKey | default "kubeconfig" }}
      {{- end }}
    type: KubeVirt
{{- end }}
  pullSecret:
    name: {{ .Values.cluster.name }}-pull-secret
  release:
    image: {{ .Values.cluster.releaseImage }}
  services:
  - service: APIServer
    servicePublishingStrategy:
      {{- if eq .Values.cluster.services.api.type "LoadBalancer" }}
      loadBalancer:
        hostname: "api.{{ .Values.cluster.name }}.{{ .Values.cluster.baseDomain }}"
      type: LoadBalancer
      {{- else if eq .Values.cluster.services.api.type "nodePort" }}
      nodePort:
        address: "api.{{ .Values.cluster.name }}.{{ .Values.cluster.baseDomain }}"
        port: {{ .Values.cluster.services.api.port | default 30000 }}
      type: NodePort
      {{- else }}
      type: Route
      {{- end }}
  - service: OAuthServer
    servicePublishingStrategy:
      type: Route
  - service: OIDC
    servicePublishingStrategy:
      type: Route
  - service: Konnectivity
    servicePublishingStrategy:
      type: Route
  - service: Ignition
    servicePublishingStrategy:
      type: Route
  - service: OVNSbDb
    servicePublishingStrategy:
      type: Route
  sshKey:
    name: {{ .Values.cluster.name }}-ssh-key
