{{- range .Values.nodePools -}}
---
apiVersion: hypershift.openshift.io/v1beta1
kind: NodePool
metadata:
  name: {{ $.Values.cluster.name }}-{{ .name }}
  namespace: {{ $.Values.cluster.hcpNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: '3'
spec:
  arch: amd64
  clusterName: {{ $.Values.cluster.name }}
  {{- if or $.Values.imageDigestMirror .nodeconfig }}
  config:
    {{ if $.Values.imageDigestMirror }}
    - name: {{ $.Values.cluster.name }}-idms-config
    {{ end }}
    {{ if .nodeconfig }}
    {{- toYaml .nodeconfig | nindent 4 }}
    {{- end }}
{{ if .nodeLabels }}
  nodeLabels:
    {{- range $key, $value := .nodeLabels }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  management:
    {{ toYaml .management | nindent 4 }}
  nodeDrainTimeout: {{ .nodeDrainTimeout }}
  platform:
{{ if eq $.Values.cluster.type "kubevirt" }}
    kubevirt:
      {{- if eq .kubevirt.network.attachDefaultPodNetwork false }}
      attachDefaultNetwork: false
      {{- end }}
      {{- if .kubevirt.networks.vlans }}
      additionalNetworks:
        {{- toYaml .kubevirt.networks.vlans | nindent 8 }}
      {{- end }}
      compute:
        cores: {{ .kubevirt.resources.cpu }}
        memory: {{ .kubevirt.resources.memory }}
      rootVolume:
        {{ if .kubevirt.enableRootVolumeCache }}
        cacheStrategy:
          type: PVC
        {{ end }}
        persistent:
          size: {{ .kubevirt.resources.rootVolumeSize }}
        type: Persistent
      {{- if .kubevirt.zone }}
      nodeSelector:
        topology.kubernetes.io/zone: {{ .kubevirt.zone }}
      {{- end }}
    type: KubeVirt
{{ end }}
{{ if eq $.Values.cluster.type "agent" }}
    type: Agent
    {{ if .agent.agentLabels }}
    agent:
      agentLabelSelector:
        {{ toYaml .agent.agentLabels | nindent 8 }}
    {{ end }}
{{ end }}
  release:
    image: {{ $.Values.cluster.releaseImage }}
  replicas: {{ .count }}

---
{{ end }}
